if (getRversion() >= "2.15.1") {
  utils::globalVariables(c(
    ".cand_len",
    ".data",
    ".dedup_key",
    ".orig_len",
    ".row_id",
    ".status_rank",
    "accepted_author",
    "accepted_genus",
    "accepted_id",
    "accepted_name",
    "accepted_species",
    "atlas_name",
    "author",
    "authority_species_author",
    "direct_match",
    "direct_match_species_within_genus",
    "fuzzy_genus_dist",
    "fuzzy_match_genus",
    "fuzzy_match_species_within_genus",
    "fuzzy_species_dist",
    "genus",
    "genus_match",
    "id",
    "input_index",
    "input_name",
    "is_accepted_name",
    "match_stage",
    "matched_author",
    "matched_genus",
    "matched_name",
    "matched_name_id",
    "mdd_author",
    "mdd_nomenclature_status",
    "mdd_original_combination",
    "mdd_species_id",
    "mdd_syn_id",
    "mdd_validity",
    "n",
    "name",
    "orig_genus",
    "orig_name",
    "orig_species",
    "query_genus",
    "query_name",
    "query_name_clean",
    "query_species",
    "sorter",
    "species",
    "specific_epithet",
    "status_rank",
    "taxon_status",
    "Genus",
    "Orig.Genus",
    "Orig.Species",
    "Species",
    ".cand_len",
    ".distribution_count",
    ".match_genus",
    ".original_leading_genus",
    ".orig_len",
    "domestic",
    "extinct",
    "family",
    "living_species",
    "max_orig_len",
    "min_orig_len",
    "orig_len",
    "original_name_combination",
    "orig_subgenus",
    "orig_subspecies",
    "query_len",
    "sci_name", 
    ".original_query_genus", ".original_query_name", ".original_query_name_clean",
     ".original_query_species", ".original_stripped_query_genus",
     ".original_stripped_query_name", ".original_stripped_query_name_clean",
     ".original_stripped_query_species", ".synonym_query_genus",
     ".synonym_query_name", ".synonym_query_name_clean", ".synonym_query_species",
     ".synonym_stripped_query_genus", ".synonym_stripped_query_name",
     ".synonym_stripped_query_name_clean", ".synonym_stripped_query_species",
     "region"
  ))
}
